#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2013 Joanna Rutkowska <joanna@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

from collections import namedtuple
import logging
import os
import subprocess
import sys
from tempfile import NamedTemporaryFile

logging.basicConfig(format='%(message)s', stream=sys.stderr)


###############################
#         Utilities
###############################

def info(msg, suffix=None):
    print(msg, end=suffix, flush=True, file=sys.stderr)

def die(msg):
    logging.error(msg)
    sys.exit(1)

def send(data):
    print(data, flush=True)

def send_b(data):
    sys.stdout.buffer.write(data)

def recv_b():
    return sys.stdin.buffer.read()


###############################
#        Image-related
###############################

def send_dimensions(png_path):
    cmd1 = ['identify', '-format', '%w', png_path]
    cmd2 = ['identify', '-format', '%h', png_path]

    try:
        width = subprocess.check_output(cmd1, text=True)
        height = subprocess.check_output(cmd2, text=True)
    except CalledProcessError:
        die("Failed to gather dimensions... Aborting")

    send(f'{width} {height}')

def send_rgb_file(rgb_path):
    with open(rgb_path, 'rb') as f:
        data = f.read()
        send_b(data)

def pdf_to_png(page, pdf_path, png_path):
    png_filename = os.path.splitext(png_path)[0]
    cmd = ['pdftocairo', pdf_path, '-png', '-f', str(page), '-l', str(page),
           '-singlefile', png_filename]

    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError:
        cmd = ['convert', pdf_path, f'png:{png_path}']
        try:
            subprocess.run(cmd, check=True)
        except subprocess.CalledProcessError:
            die(f'Page {page} conversion failed (PDF->PNG): {err}')

def png_to_rgb(png_path, rgb_path):
    depth = 8
    cmd = ['convert', png_path, '-depth', str(depth), f'rgb:{rgb_path}']

    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError:
        die(f'Page {page} conversion failed (PNG->RGB): {err}')


###############################
#         File-related
###############################

def get_tmp_files():
    Files = namedtuple('Files', ['pdf', 'png', 'rgb'])
    suffixes = ('', '.png', '.rgb')
    paths = []

    for suffix in suffixes:
        with NamedTemporaryFile(prefix='qpdf-conversion-', suffix=suffix) as f:
            paths.append(f.name)

    return Files(pdf=paths[0], png=paths[1], rgb=paths[2])

def make_tmp_files(paths):
    for path in paths:
        with open(path, 'wb') as f:
            f.write(b'')


###############################
#         PDF-related
###############################

def recv_pdf(pdf_path):
    with open(pdf_path, 'wb') as f:
        data = recv_b()
        f.write(data)

def get_page_count(pdf_path):
    pages = 0
    output = None
    cmd = ['pdfinfo', pdf_path]

    try:
        output = subprocess.check_output(cmd)
    except subprocess.CalledProcessError:
        info(f'Probably not a PDF...')
    else:
        for line in output.decode().splitlines():
            if 'Pages:' in line:
                pages = int(line.split(':')[1])

    return pages

def process_pdf(paths):
    page = 1

    pages = get_page_count(paths.pdf)
    send(pages)

    while (page <= pages):
        pdf_to_png(page, paths.pdf, paths.png)
        send_dimensions(paths.png)
        png_to_rgb(paths.png, paths.rgb)
        send_rgb_file(paths.rgb)
        page += 1


###############################
#            Main
###############################

def main():
    paths = get_tmp_files()
    make_tmp_files(paths)
    recv_pdf(paths.pdf)
    process_pdf(paths)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        die("KeyboardInterrupt... aborting!")
